version: '3.6'
services:
  django:
    build:
      context: .
      dockerfile: django-dockerfile
    image: markiiank/devops-labs-images:compose-django
    container_name: django
    networks:
      - publ
    ports:
      - 8000:8000
  monitoring:
    build:
      context: .
      dockerfile: monitoring-dockerfile
    image: markiiank/devops-labs-images:compose-monitoring
    container_name: monitoring
    depends_on:
      - django
    network_mode: host
    volumes:
      - monit-log:/app/

volumes:
  monit-log:
    driver: local

networks:
  publ:
    driver: bridge
